Add files via upload
DragonMiner minigames, has errors, needs to be fixed, tested on haha's computer localhost minecraft server using hte same spigot as dragonminer, using the same spigot imported and has all DM Custom Made plugins(Almost)

-Haha

Error in logs:
[14:02:09 ERROR]: Could not load 'plugins\DMMinigames.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: Cannot find main class `union.haha.minigames.Main'
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:42) ~[craftbukkit-latest.jar:git-Bukkit-1953f52]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[craftbukkit-latest.jar:git-Bukkit-1953f52]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:328) ~[craftbukkit-latest.jar:git-Bukkit-1953f52]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [craftbukkit-latest.jar:git-Bukkit-1953f52]
        at org.bukkit.craftbukkit.v1_10_R1